version: '2'

networks:
  default:

services:

  orderer.hf.chainhero.io:
    image: hyperledger/fabric-orderer:x86_64-1.0.5
    container_name: orderer.hf.chainhero.io
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISPROFILE=ChainHero
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=hf.chainhero.io
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/hf.chainhero.io/orderers/orderer.hf.chainhero.io/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/hf.chainhero.io/orderers/orderer.hf.chainhero.io/tls:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      default:
        aliases:
          - orderer.hf.chainhero.io

  ca.org1.hf.chainhero.io:
    image: hyperledger/fabric-ca:x86_64-1.0.5
    container_name: ca.org1.hf.chainhero.io
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.hf.chainhero.io
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.hf.chainhero.io-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/922c10582b67167dd4c712ba248dd2465651a199b48764c946a6b5361dda2568_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.hf.chainhero.io-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/922c10582b67167dd4c712ba248dd2465651a199b48764c946a6b5361dda2568_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.hf.chainhero.io/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      default:
        aliases:
          - ca.org1.hf.chainhero.io
#  cli:
#    tty: true
#    container_name: cli
#    image: hyperledger/fabric-tools
#    environment:
#      - GOPATH=/opt/gopath
#      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#      - CORE_LOGGING_LEVEL=DEBUG
#      - CORE_PEER_ID=cli
#      - CORE_PEER_ADDRESS=peer0.org1.hf.chainhero.io:7051
#      - CORE_PEER_LOCALMSPID=org1.hf.chainhero.io
#      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
#    working_dir: /opt/gopath/src/chaincodedev
#    command: /bin/bash -c 'sleep 6000000'
#    volumes:
#        - /var/run/:/host/var/run/
#        - ./crypto-config/peerOrganizations/org1.hf.chainhero.io/peers/peer0.org1.hf.chainhero.io/msp:/etc/hyperledger/msp
#        - ./../chaincode:/opt/gopath/src/chaincodedev/chaincode
#        - ./:/opt/gopath/src/chaincodedev/
#    depends_on:
#      - orderer.hf.chainhero.io
#      - peer0.org1.hf.chainhero.io
#  chaincode:
#    tty: true
#    container_name: chaincode
#    image: hyperledger/fabric-ccenv
#    environment:
#      - GOPATH=/opt/gopath
#      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#      - CORE_LOGGING_LEVEL=DEBUG
#      - CORE_PEER_ID=example02
#      - CORE_PEER_ADDRESS=peer0.org1.hf.chainhero.io:7051
#      - CORE_PEER_LOCALMSPID=org1.hf.chainhero.io
#      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
#    working_dir: /opt/gopath/src/chaincode
#    command: /bin/bash -c 'sleep 6000000'
#    volumes:
#        - /var/run/:/host/var/run/
#        - ./crypto-config/peerOrganizations/org1.hf.chainhero.io/peers/peer0.org1.hf.chainhero.io/msp:/etc/hyperledger/msp
#        - ./../chaincode:/opt/gopath/src/chaincode
#    depends_on:
#      - orderer.hf.chainhero.io
#      - peer0.org1.hf.chainhero.io
  peer0.couchdb:
    container_name: peer0.couchdb
#    image: hyperledger/fabric-couchdb
    image: klaemo/couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    ports:
      - 5984:5984
    networks:
      default:
        aliases:
          - peer0.couchdb
  peer0.org1.hf.chainhero.io:
    image: hyperledger/fabric-peer:x86_64-1.0.5
    container_name: peer0.org1.hf.chainhero.io
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=chainhero
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.hf.chainhero.io
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer0.org1.hf.chainhero.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.hf.chainhero.io:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org1.hf.chainhero.io
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.org1.hf.chainhero.io
      - CORE_CHAINCODE_DEPLOYTIMEOUT=300s
      - CORE_CHAINCODE_STARTUPTIMEOUT=300s

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start #--peer-chaincodedev=true -o orderer.hf.chainhero.io:7050
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.hf.chainhero.io/peers/peer0.org1.hf.chainhero.io/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/org1.hf.chainhero.io/peers/peer0.org1.hf.chainhero.io/tls:/var/hyperledger/tls
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer.hf.chainhero.io
      - peer0.couchdb
    links:
      - orderer.hf.chainhero.io
    networks:
      default:
        aliases:
          - peer0.org1.hf.chainhero.io
  # peer1.couchdb:
  #   container_name: peer1.couchdb
  #   image: hyperledger/fabric-couchdb
  #   # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
  #   # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
  #   environment:
  #     - COUCHDB_USER=admin
  #     - COUCHDB_PASSWORD=admin
  #   ports:
  #     - 6984:5984
  #   networks:
  #     default:
  #       aliases:
  #         - peer1.couchdb
  # peer1.org1.hf.chainhero.io:
  #   image: hyperledger/fabric-peer:x86_64-1.0.5
  #   container_name: peer1.org1.hf.chainhero.io
  #   environment:
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - CORE_VM_DOCKER_ATTACHSTDOUT=true
  #     - CORE_LOGGING_LEVEL=DEBUG
  #     - CORE_PEER_NETWORKID=chainhero
  #     - CORE_PEER_PROFILE_ENABLED=true
  #     - CORE_PEER_TLS_ENABLED=true
  #     - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
  #     - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
  #     - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
  #     - CORE_PEER_ID=peer1.org1.hf.chainhero.io
  #     - CORE_PEER_ADDRESSAUTODETECT=true
  #     - CORE_PEER_ADDRESS=peer1.org1.hf.chainhero.io:7051
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.hf.chainhero.io:7051
  #     - CORE_PEER_GOSSIP_USELEADERELECTION=true
  #     - CORE_PEER_GOSSIP_ORGLEADER=false
  #     - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
  #     - CORE_PEER_LOCALMSPID=org1.hf.chainhero.io
  #     - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
  #     - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer1.org1.hf.chainhero.io
  #     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1.couchdb:5984
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #   command: peer node start --peer-chaincodedev=true
  #   volumes:
  #     - /var/run/:/host/var/run/
  #     - ./crypto-config/peerOrganizations/org1.hf.chainhero.io/peers/peer1.org1.hf.chainhero.io/msp:/var/hyperledger/msp
  #     - ./crypto-config/peerOrganizations/org1.hf.chainhero.io/peers/peer1.org1.hf.chainhero.io/tls:/var/hyperledger/tls
  #   ports:
  #     - 8051:7051
  #     - 8053:7053
  #   depends_on:
  #     - orderer.hf.chainhero.io
  #     - peer1.couchdb
  #   links:
  #     - orderer.hf.chainhero.io
  #   networks:
  #     default:
  #       aliases:
  #         - peer1.org1.hf.chainhero.io