[[constraint]]
  # v1.0.5
  name = "github.com/hyperledger/fabric"
  revision = "b17afeb9da2ae34ce9dd76de558fbd23623fb186"

[[constraint]]
  name = "github.com/hyperledger/fabric-sdk-go"
  revision = "614551a752802488988921a730b172dada7def1d"